import {
  faCalendarDays,
  faCreditCard,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import "../../styles/User-Styles/CreateCardModal.css";

function CreateCardModal({
  setIsCreateCardModalOpen,
  setCards,
  userFirstName,
  userLastName,
}) {
  const [newCard, setNewCard] = useState({
    cardNumber: "XXXX XXXX XXXX XXXX",
    expiryDate: "MM/YY",
    cvv: "XXX",
    cardHolderName: `${userFirstName} ${userLastName}`,
  });
  const [message, setMessage] = useState("");
  const [acknowledgeDisclaimer, setAcknowledgeDisclaimer] = useState(false);

  return (
    <div className="create-card-modal-container">
      <div className="create-card-modal-content">
        <div className="create-card-modal-header">
          <h1>Create a new card</h1>
          <button
            className="billing-info-modal-close"
            onClick={() => setIsCreateCardModalOpen(false)}
          >
            X
          </button>
        </div>
        <div className="message-wrapper">
          {message && <p className="submit-message message">{message}</p>}
        </div>
        <div className="form-wrapper">
          <form className="card-form">
            <div className="card-form-row ">
              <div className="field">
                <label htmlFor="cardNumber">Card Number</label>
                <div className="input-icon-wrapper">
                  <input
                    id="cardNumber"
                    type="text"
                    value={newCard.cardNumber}
                    disabled
                  />
                  <FontAwesomeIcon icon={faCreditCard} />
                </div>
              </div>
            </div>
            <div className="card-form-row ">
              <div className="field">
                <label htmlFor="expiryDate">Expiry Date</label>
                <div className="input-icon-wrapper">
                  <input
                    id="expiryDate"
                    type="text"
                    value={newCard.expiryDate}
                    disabled
                  />
                  <FontAwesomeIcon icon={faCalendarDays} />
                </div>
              </div>
              <div className="field ">
                <label htmlFor="cvv">CVC/CVV</label>
                <input id="cvv" type="text" value={newCard.cvv} disabled />
              </div>
            </div>
            <div className="card-form-row ">
              <div className="field">
                <label htmlFor="cardHolderName">Card holder name</label>
                <input
                  id="cardHolderName"
                  type="text"
                  value={newCard.cardHolderName}
                  disabled
                />
              </div>
            </div>

            <div className="gen-button-wrapper">
              <button className="generate-button" type="button">
                Generate Card
              </button>
            </div>
          </form>
        </div>
        <div className="disclaimer-wrapper">
          <div className="disclaimer-container">
            <small className="disclaimer">
              Disclaimer: This site is a portfolio demonstration. It does not
              process real transactions, and it does not store any real payment
              or personal information. The "card" you "create" here is purely
              fictional and generated by the system for demonstration purposes.
            </small>
            <label className="checkbox-container">
              <input
                type="checkbox"
                className="hidden-checkbox"
                checked={acknowledgeDisclaimer}
                onChange={(e) => setAcknowledgeDisclaimer(e.target.checked)}
              />
              <span className="custom-checkbox">
                {acknowledgeDisclaimer && <FontAwesomeIcon icon={faCheck} />}
              </span>
            </label>
          </div>
        </div>
        <div className="button-wrapper">
          <button className="submit-button" type="submit">
            Submit
          </button>
        </div>
      </div>
    </div>
  );
}

export default CreateCardModal;
